<template>
  <div style="text-align: left">
    <el-row :gutter="10" style="margin-bottom: 10px">
      <el-col span="12">
        <el-input
          placeholder="请输入内容"
          prefix-icon="el-icon-search"
          size="small"
          style="width: 240px"
          v-model="searchKey">
        </el-input>
        <el-button
          @click="searchInTable"
          icon="el-icon-search"
          size="small"
          type="primary">
          搜索
        </el-button>
      </el-col>
      <el-col span="12" style="text-align: right;">
        <el-button @click="showDialog" plain="true" size="small" type="primary">添加</el-button>
        <el-button @click="handleDelete" plain="true" size="small" type="danger">删除</el-button>
        <el-button @click="handleUpdate" plain="true" size="small">修改</el-button>
      </el-col>
    </el-row>
    <el-row>
      <EmployeeAddedDialog ref="employeeAddedDialog"></EmployeeAddedDialog>
      <EmployeeUpdateDialog ref="employeeUpdateDialog"></EmployeeUpdateDialog>
    </el-row>
    <el-row style="margin-bottom: 10px">
      <el-table
        :data="tableShowData"
        @selection-change="handleSelectChange"
        border
        height="800"
        max-height="800"
        size="mini"
        stripe
        style="width: 100%">
        <el-table-column
          align="left"
          type="selection"
          width="30">
        </el-table-column>
        <el-table-column
          align="center"
          fixed
          label="名称"
          sortable="true"
          prop="name"
          width="250">
        </el-table-column>
        <el-table-column
          label="类型"
          align="center"
          prop="type"
          width="150">
        </el-table-column>
        <el-table-column
          align="center"
          label="打卡器"
          prop="cardReader.name"
          width="100">
        </el-table-column>
        <el-table-column
          align="center"
          label="监控状态"
          prop="state"
          width="100">
        </el-table-column>
        <el-table-column
          label="报警状态"
          align="center"
          sortable="true"
          prop="alarming"
          width="100">
          <template slot-scope="scope">
            <span>{{ scope.row.alarming?'报警中':'正常' }}</span>
          </template>
        </el-table-column>
        <el-table-column
          label="报警时间"
          align="center"
          sortable="true"
          prop="alarmTime"
          width="200">
          <template slot-scope="scope">
            <span>{{ scope.row.alarmTime }}</span>
          </template>
        </el-table-column>
        <el-table-column
          label="报警时长"
          align="center"
          sortable="true"
          prop="alarmingSpan"
          width="100">
        </el-table-column>
        <el-table-column
          label="推送"
          align="center"
          prop="pushLevel"
          width="100">
        </el-table-column>
        <el-table-column
          align="center"
          label="员工编号"
          prop="employee.workId"
          width="150">
        </el-table-column>
        <el-table-column
          align="center"
          label="员工姓名"
          prop="employee.name"
          width="150">
        </el-table-column>
        <el-table-column
          align="center"
          label="组长编号"
          prop="master.workId"
          width="150">
        </el-table-column>
        <el-table-column
          align="center"
          label="组长姓名"
          prop="master.name"
          width="150">
        </el-table-column>
      </el-table>
    </el-row>
  </div>
</template>

<script>
  import moment from 'moment'
  import EmployeeAddedDialog from './EmployeeAddedDialog'
  import EmployeeUpdateDialog from './EmployeeUpdateDialog'

  export default {
    name: 'EmployeeInfo',

    components: {
      EmployeeAddedDialog,
      EmployeeUpdateDialog
    },
    data () {
      return {
        searchKey: '',
        tableShowData: [],
        alarmInfo: [
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:false,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:17,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:17,
              name:'当班员工2',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id: 1,
            name: '7号线中轧测厚',
            type: '测厚系统',
            cardReaderId: 1,
            state: '正常',
            alarming: true,
            alarmTime: '2019-09-21 16:40:23',
            alarmingSpan: 50,
            pushLevel: '无推送',
            employeeId: 15,
            masterId: 23,
            cardReader: {
              id: 1,
              name: '1号读卡器',
              value: '12345678'
            },
            employee: {
              id: 15,
              name: '当班员工1',
              workId: '340823',
              position: '员工',
              email: ''
            },
            master: {
              id: 23,
              name: '组长1',
              workId: '99999',
              position: '班组长',
              email: '1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            }
          },
          {
            id:1,
            name:'7号线中轧测厚',
            type:'测厚系统',
            cardReaderId:1,
            state:'正常',
            alarming:true,
            alarmTime:'2019-09-21 16:40:23',
            alarmingSpan:50,
            pushLevel:'无推送',
            employeeId:15,
            masterId:23,
            cardReader:{
              id:1,
              name:'1号读卡器',
              value:'12345678'
            },
            employee:{
              id:15,
              name:'当班员工1',
              workId:'340823',
              position:'员工',
              email:''
            },
            master:{
              id:23,
              name:'组长1',
              workId:'99999',
              position:'班组长',
              email:'1721662545@qq.com'
            },
          }
        ],
        selectedColums: []
      }
    },
    methods: {
      handleDelete () {
        if (this.selectedColums.length <= 0) {
          return
        }
        if (!confirm('确认删除?')) {
          return
        }
        let deleteIds = []
        for (let index in this.selectedColums) {
          deleteIds.push(this.selectedColums[index].id)
        }
        this.axios({
          method: 'post',
          url: '/employeeInfo/deleteEmployees',
          data: deleteIds,
        }).then(resp => {
          if (resp && resp.status == 200 && resp.data == true) {
            alert('删除成功')
            this.getInfosByPage(1)
            return
          }
          alert('删除失败')
        })
      },
      handleUpdate () {
        if (this.selectedColums.length == 1) {
          this.$refs.employeeUpdateDialog.show(this.selectedColums[0])
        }
      },
      getInfosByPage (page, size = 20) {
        this.tableShowData = this.alarmInfo;
      },
      //TODO ......
      searchInTable () {
        let tempArr = [];
        tempArr = searchInObj(this.searchKey,this.alarmInfo);
        return tempArr;
      },
      searchInObj(key,obj) {
        let tempArr =[];
        for (let index in obj) {
          if(typeof obj[index]  == 'object') {
            searchInObj(key in obj[index]);
          }else {
            if (key && obj[index] && obj[index].match(key)) {
              tempArr.push(obj[index])
            }
          }
        }
        return tempArr;
      },
      handleSelectChange (selection) {
        this.selectedColums = selection
      },
      showDialog () {
        this.$refs.employeeAddedDialog.show()
      }
    },
    mounted: function () {
      this.getInfosByPage(1)
    }
  }

</script>

<style scoped>

</style>
